### ISSUE TITLE
Video Broken for YouTube URL

### ISSUE THREAD

**Issue by wingman-jr-addon** [wingman-jr-addon/wingman_jr#127]
https://www.youtube.com/watch?v=6kzwAt_tcKM

**Comment by wingman-jr-addon** [comment]
23:23:47.447 Error parsing EBML somewhere around 357 ebml.js:109:17
23:23:47.448 YTVWEBM: No fragments for CPN no53ty_MF27BgZ0R for 26100 at quality 247 at range start 0, continuing... background_video.js:619:25
23:23:47.676 Error parsing EBML somewhere around 357 ebml.js:109:17
23:23:47.676 YTVWEBM: No fragments for CPN no53ty_MF27BgZ0R for 26106 at quality 247 at range start 0, continuing... background_video.js:619:25
23:23:52.489 Error parsing EBML somewhere around 357 ebml.js:109:17
23:23:52.489 YTVWEBM: No fragments for CPN no53ty_MF27BgZ0R for 26110 at quality 244 at range start 0, continuing... background_video.js:619:25
23:24:00.463 Error parsing EBML somewhere around 357 ebml.js:109:17
23:24:00.464 YTVWEBM: No fragments for CPN no53ty_MF27BgZ0R for 26122 at quality 243 at range start 0, continuing... background_video.js:619:25
23:24:26.600 Error parsing EBML somewhere around 357 ebml.js:109:17
23:24:26.600 YTVWEBM: No fragments for CPN g8dfKDnugAxwg_AA for 26256 at quality 244 at range start 0, continuing... background_video.js:619:25
23:24:40.808 Error parsing EBML somewhere around 357 ebml.js:109:17
23:24:40.808 YTVWEBM: No fragments for CPN g8dfKDnugAxwg_AA for 26263 at quality 243 at range start 0, continuing...

**Comment by wingman-jr-addon** [comment]
Assigning this medium priority because I haven't yet found many videos it seems to affect. User reports of video failures would be appreciated.

**Comment by wingman-jr-addon** [comment]
Looked into the issue and the EBML parsing was not directly at fault - the expected video events never got called.
